FROM node:16.15.0-alpine3.14 AS production

RUN apk update && apk add bash

RUN mkdir -p /usr/src/app

RUN yarn global add pm2

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY package.json ./
COPY yarn.lock ./

RUN yarn install --production=false

COPY . .

RUN yarn build

CMD [ "pm2-runtime", "start", "yarn", "--interpreter","bash", "--", "start" ]
