version: "3.8"
services:
    ransom_dev_backend:
        container_name: rw_server_dev
        image: rw_server_dev:1.0.0
        build:
            context: ./server
            target: development
            dockerfile: ./Dockerfile
        command: yarn start:dev
        #command: ["wait-for-it.sh", "postgres:5432", "--","yarn", "start:dev"]
        # env_file:
        #     - /server/.env
        ports:
            - 4000:4000
            #- 4001:9229
        networks:
            - database
            - hunted_backend
            - frontend
        volumes:
            - ./server:/usr/src/app
            - /usr/src/app/node_modules
            - ../uploads:/usr/src/app/uploads
            - ../texts:/usr/src/app/texts
        restart: unless-stopped

    ransom_dev_frontend:
        depends_on:
            - ransom_dev_backend
        container_name: rw_client_dev
        build:
            context: ./client
            target: development
            dockerfile: ./Dockerfile
        ports:
            - 8082:3002
        networks:
            - frontend
        volumes:
            - ./client:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
networks:
    database:
        external: true
        name: "database"
    hunted_backend:
        external: true
        name: "hunted_backend"
    backend:
        driver: bridge
    frontend:
        driver: bridge


